export const experimentMeta = {
  audience: 'EFund summer internship final demonstration',
  project: 'StockBench × DeepSeek LLM Trading Agent',
  period: '2025-03-03 → 2025-06-30',
  capital: '$100,000',
  universe: 'DJIA top 20',
  model: 'deepseek-v4-flash',
  strategy: 'llm_decision / dual agent / offline_only',
};

export const architectureLayers = [
  {
    id: '01',
    title: '数据特征层',
    label: 'feature construction',
    role: '把行情、新闻、持仓和基本面整理成 prompt-ready features。',
    inputs: ['open / close_7d', 'news top_k_events', 'position_state', 'fundamental_data'],
    code: 'stockbench/core/features.py',
    tone: 'cyan',
  },
  {
    id: '02',
    title: '选股层',
    label: 'tradable universe',
    role: '固定 DJIA top 20 股票池，按当日数据可用性进入决策链路。',
    inputs: ['GS', 'MSFT', 'HD', 'V', 'CAT', 'AAPL', 'AMZN', 'JNJ'],
    code: 'config.yaml / symbols_universe',
    tone: 'cyan',
  },
  {
    id: '03',
    title: '候选排序层',
    label: 'candidate focus',
    role: '用结构化信号降低横向比较负担；排序是辅助，不直接替代决策。',
    inputs: ['momentum_7d_rank_pct', 'return_5d_rank_pct', 'relative_strength_bucket'],
    code: '_attach_quant_factor_features()',
    tone: 'amber',
  },
  {
    id: '04',
    title: '交易记忆层',
    label: 'anti-overtrade memory',
    role: '给每只股票保留历史动作与理由，约束短期重复低质量交易。',
    inputs: ['history', 'action', 'target_cash_amount', 'reasons', 'confidence'],
    code: 'decision_history / previous_decisions',
    tone: 'blue',
  },
  {
    id: '05',
    title: 'Prompt 决策层',
    label: 'structured decision task',
    role: 'fundamental filter 先判断分析深度，decision agent 输出 JSON 决策。',
    inputs: ['portfolio_info', 'symbols', 'history', 'filter_reasoning'],
    code: 'decision_agent_v1.txt',
    tone: 'blue',
  },
  {
    id: '06',
    title: '订单约束层',
    label: '5-day cooldown',
    role: 'LLM 先建议，执行后处理只做低权限稳定性约束。',
    inputs: ['cooldown_days = 5', '反向交易拦截', 'final order'],
    code: 'F5_COOLDOWN_5D / F6',
    tone: 'red',
  },
  {
    id: '07',
    title: '风险控制层',
    label: 'soft warning boundary',
    role: '风险信息保留为提示；强覆盖版本在实验中容易过度保守。',
    inputs: ['volatility', 'drawdown', 'concentration', 'risk note'],
    code: 'Q1 / risk guardrail / F10 notes',
    tone: 'red',
  },
  {
    id: '08',
    title: '归因分析层',
    label: 'evidence ledger',
    role: '记录模块、干预、指标和版本差异，支撑最终实验结论。',
    inputs: ['metrics', 'trades', 'intervention counts', 'future return attribution'],
    code: 'scripts/analyze_experiment_attribution.py',
    tone: 'blue',
  },
];

export const ablationRuns = [
  {
    id: 'B0',
    name: 'DeepSeek 基线',
    design: '纯 LLM；无反思、无基本面、无结构化量化',
    returnPct: 2.56,
    maxDrawdown: -10.47,
    sharpe: 0.404,
    sortino: 0.034,
    trades: 564,
    modules: ['prompt'],
    verdict: '起点：收益为正，但交易频繁，缺少行为约束。',
    status: 'base',
  },
  {
    id: 'Q1',
    name: '结构化量化',
    design: '动量、趋势、风险信号结构化输入',
    returnPct: -7.54,
    maxDrawdown: -13.99,
    sharpe: -0.881,
    sortino: -0.063,
    trades: 257,
    modules: ['quant', 'prompt'],
    verdict: '负面结果：alpha 与 risk 混合，错过反弹。',
    status: 'rejected',
  },
  {
    id: 'FUND1',
    name: '基本面清洗',
    design: '清洗、分桶后的基本面信号',
    returnPct: 3.35,
    maxDrawdown: -11.61,
    sharpe: 0.471,
    sortino: 0.038,
    trades: 351,
    modules: ['features', 'fundamental', 'prompt'],
    verdict: '有效：输入质量改善，交易数下降。',
    status: 'kept',
  },
  {
    id: 'C1',
    name: '硬执行约束',
    design: '限制交易数、换手和最小成交额',
    returnPct: 1.58,
    maxDrawdown: -10.98,
    sharpe: 0.302,
    sortino: 0.023,
    trades: 75,
    modules: ['constraints'],
    verdict: '证明约束有效，但单独使用过强。',
    status: 'limited',
  },
  {
    id: 'M1',
    name: '选择性记忆',
    design: '历史错误记忆与反思上下文',
    returnPct: -0.02,
    maxDrawdown: -11.2,
    sharpe: 0.126,
    sortino: 0.009,
    trades: 227,
    modules: ['memory'],
    verdict: 'generic reflection 过于保守，需改成更精确的 anti-overtrade memory。',
    status: 'learned',
  },
  {
    id: 'F5',
    name: '基本面 + 记忆',
    design: '清洗基本面 + 个股级交易行为记忆',
    returnPct: 3.83,
    maxDrawdown: -12.41,
    sharpe: 0.525,
    sortino: 0.045,
    trades: 363,
    modules: ['features', 'fundamental', 'memory', 'prompt'],
    verdict: '结构性改进：收益和 Sharpe 继续提升。',
    status: 'kept',
  },
  {
    id: 'F6',
    name: '5 日冷却主线',
    design: '基本面清洗 + 交易记忆 + 5 日冷却',
    returnPct: 3.9913,
    maxDrawdown: -9.1603,
    sharpe: 0.556719,
    sortino: 0.043074,
    trades: 261,
    modules: ['features', 'fundamental', 'memory', 'cooldown', 'attribution'],
    verdict: '综合最优：收益、回撤、交易次数最均衡。',
    status: 'winner',
  },
  {
    id: '10D',
    name: '10 日冷却',
    design: '更强冷却窗口；限制更重',
    returnPct: 0.57,
    maxDrawdown: -11.81,
    sharpe: 0.188,
    sortino: 0.016,
    trades: 240,
    modules: ['memory', 'cooldown'],
    verdict: '边界结果：过强 cooldown 压制收益。',
    status: 'limited',
  },
  {
    id: 'RISK',
    name: '量化风险覆盖',
    design: '量化确认、否决、仓位调整信号',
    returnPct: -2.6,
    maxDrawdown: -13.79,
    sharpe: -0.163,
    sortino: -0.012,
    trades: 289,
    modules: ['quant', 'risk'],
    verdict: '负面结果：hard veto 可能挡掉反弹机会。',
    status: 'rejected',
  },
  {
    id: 'F10',
    name: '软执行尝试',
    design: '小额偏离跳过，中等偏离部分执行',
    returnPct: 2.9943,
    maxDrawdown: -10.2283,
    sharpe: 0.477596,
    sortino: 0.041265,
    trades: 436,
    modules: ['soft-exec'],
    verdict: '未超过 F6；不升级为主线。',
    status: 'limited',
  },
];

export const moduleColumns = [
  { key: 'features', label: '清洗特征' },
  { key: 'fundamental', label: '基本面' },
  { key: 'memory', label: '记忆' },
  { key: 'cooldown', label: '5D 冷却' },
  { key: 'quant', label: '量化' },
  { key: 'risk', label: '风险覆盖' },
  { key: 'soft-exec', label: '软执行' },
];
